### Get all Accounts
GET http://localhost:8080/api/accounts
Accept: application/json

### Get Account by ID
GET http://localhost:8080/api/accounts/2
Accept: application/json

### Create a new Account
POST http://localhost:8080/api/accounts
Content-Type: application/json
Accept: application/json

{
  "userName": "dreniiii",
  "balance": 0
}

### Delete a Account
DELETE http://localhost:8080/api/accounts/1
Accept: application/json




### BANKS

### Get all Banks
GET http://localhost:8080/api/banks
Accept: application/json

### Get Bank by ID
GET http://localhost:8080/api/banks/1
Accept: application/json

### Create a new Bank
POST http://localhost:8080/api/banks
Content-Type: application/json
Accept: application/json

{
  "bankName": "Raiffeisen",
  "totalTransactionFeeAmount": 0,
  "totalTransferAmount":  0,
  "transactionFlatFeeAmount": 1,
  "transactionPercentFeeValue":  3
}

### Delete a Account
DELETE http://localhost:8080/api/accounts/1
Accept: application/json